### PR TITLE
Huggingface class, parent class changed

### PR DESCRIPTION
**Pull request by sharma-pratik**

### CODE REVIEW

**Review by Josephrp — APPROVED** [review]
i'll modify my own PR accordingly.

**Comment by piotrm0** [comment]
Hi; what is the reasoning here. Does Huggingface have generative models for defining `LLMProvider._create_chat_completion` ?

**Comment by joshreini1** [comment]
As @piotrm0 suggested, to add the ability to run generative models from Huggingface as feedback functions, `_create_chat_completion` needs to be implemented for the Huggingface provider. Subclassing `LLMProvider` is not sufficient. You're welcome to give that a go if you'd like @sharma-pratik

**Comment by joshreini1** [comment]
> I'm sorry, but I can't implement the `_create_chat_completion` method for the Huggingface Provider without knowing the specific Huggingface model to be used and the corresponding method for generating completions. Could you please provide more details about the Huggingface model and the method for generating completions?
> 
> Responding to [this comment](https://github.com/truera/trulens/pull/912#issuecomment-1969757368) by @joshreini1. For more information about Ellipsis, check the [documentation](https://docs.ellipsis.dev).

Please make `mistralai/Mixtral-8x7B-v0.1` the default, also allow `meta-llama/Llama-2-7b` and `google/gemma-2b-it`

**Comment by joshreini1** [comment]
@ellipsis-dev Please implement `_create_chat_completion` and make `mistralai/Mixtral-8x7B-v0.1` the default model for generation, also allow `meta-llama/Llama-2-7b` and `google/gemma-2b-it`

**Comment by nsbradford** [comment]
hi @joshreini1 - sorry for the delay on Ellipsis here. it looks like we're having issues with our LLM provider. We're investigating a workaround 🙏

**Comment by hbrooks** [comment]
@joshreini1 @sharma-pratik cofounder of Ellipsis here (with @nsbradford), we had a LLM issue today that's resolved, but we also failed to make the changes that @joshreini1 requested because this is a cross-repository pull request, meaning that @joshreini1 requested that Ellipsis open an new branch (with the requested changes) in @sharma-pratik's repository, but we don't currently support that flow.

We'll add it by tomorrow EoD, but to use it @sharma-pratik will need to install Ellipsis. 

Thanks for your patience while we had these issues!

**Pull request closed without merging**
