### PR TITLE
Allow Feedback.run with args even if they had selectors specified.

### PR DESCRIPTION
**Pull request by piotrm0**
- Small adjustments to litellm provider. Updated version lowerbound and removed upper bound as the python 3.8 issue seems to have been addressed on their end.

- Adjusted Feedback.run so one can run it without records/apps and even if the Feedback had selectors provided:
```python
f = Feedback(...).on(...)

f.run(text1="something", text2="something")
```
Previously this would not work if text1 or text2 had selectors set but now one can provide values to .run itself and if all values are provided, no selector will be used and one can run the feedback without the data that would otherwise be needed for the selector (record, app).

### CODE REVIEW

**Review by joshreini1 — APPROVED** [review]

**Review by joshreini1 — CHANGES_REQUESTED** [review]
This is breaking the release pipeline - why is this needed?

**Comment by piotrm0** [comment]
Release pipeline is broken since this doesn't include the recent fix that was in a different PR.

**Comment by joshreini1** [comment]
Got it - still curious in what cases you would want to provide values to f.run itself?

**Review by joshreini1 — APPROVED** [review]

**Comment by piotrm0** [comment]
> Got it - still curious in what cases you would want to provide values to f.run itself?

For simpler testing of feedback functions. I saw people unsure how to run feedback functions after they define them. We explained you can get f.imp but with f.run(...), it may be more direct for them. Also, this allows you to run partially on selected values and partially on other values. Like (f.run(record=record, app=app, text2="something else")) so that the value for one arg (text1) is retrieved from record, but value for a different input (text2) is provided explicitly. May be used for testing.

**Comment by joshreini1** [comment]
Very helpful - thanks!

**Pull request merged**
