### PR TITLE
Add snowflake PrPr notebook

### PR DESCRIPTION
**Pull request by sfc-gh-dhuang**
# Description

1. Adding example notebook so that this can be shared easily w/ PrPr customers
2. Updating the model from `mistral-large` to `mistral-large2` for `Complete` python API to avoid issue with the new REST backend.

## Other details good to know for developers

Please include any other details of this change useful for _TruLens_ developers.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
  not work as expected)
- [ ] New Tests
- [ ] This change includes re-generated golden test results
- [ ] This change requires a documentation update

### CODE REVIEW

**Review by sfc-gh-chu — APPROVED** [review]

**Comment by sfc-gh-chu** [comment]
Can we add some prerequisite steps with getting setup (like how to ingest the retrieval data and setup Cortex Search)

**Comment by sfc-gh-dhuang** [comment]
> Can we add some prerequisite steps with getting setup (like how to ingest the retrieval data and setup Cortex Search)

I was assuming the audience of this notebook should be already looking at our PrPr doc so didn't repeat the steps in the nb. https://drive.google.com/file/d/1UUjZjEYyuXPPc2fmxzYf3ecZEBkWQIiW/view

**Comment by sfc-gh-chu** [comment]
if we add this in the examples directory it'll also show up on the docs site though

**Comment by sfc-gh-dhuang** [comment]
> if we add this in the examples directory it'll also show up on the docs site though

talked offline - added markdown to include part of the PrPr PDF doc

**Pull request merged**
