### PR TITLE
Add support for Azure, Palm, Anthropic, Cohere, Hugging Face Llama2 70b Models - using litellm

### PR DESCRIPTION
**Pull request by ishaan-jaff**
This PR adds support for models from all the above mentioned providers using https://github.com/BerriAI/litellm/

All LLM API Models are guaranteed to have the same Input/Output interface 

Here's a sample of how it's used:

```python
from litellm import completion

## set ENV variables
# ENV variables can be set in .env file, too. Example in .env.example
os.environ["OPENAI_API_KEY"] = "openai key"
os.environ["COHERE_API_KEY"] = "cohere key"
os.environ["HF_API_TOKEN"] = "hf-key"

messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# hugging face llama2 call
completion(model="meta-llama/llama-2-7b-hf", messages=messages)

# hugging face llama2 Guanaco call
completion(model="TheBloke/llama-2-70b-Guanaco-QLoRA-fp16", messages=messages)

# cohere call
response = completion("command-nightly", messages)

# anthropic call
response = completion(model="claude-instant-1", messages=messages)
```

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
@rshih32 @joshreini1 can you please take a look at this PR when you get a chance😊

If this looks good happy to add more tests / docs

**Comment by piotrm0** [comment]
> if it makes sense using litellm can also simplify how you're calling them

Hi. I noticed that litellm only supports completion and embedding models. We are using huggingface mostly for classification. How would we use litellm to help with those?

**Comment by joshreini1** [comment]
> @rshih32 @joshreini1 can you please take a look at this PR when you get a chance😊
> 
> If this looks good happy to add more tests / docs

Hey @ishaan-jaff,
Thanks for the PR - this is a problem we've been thinking about internally. Supporting a wide variety of models for use as feedback functions is an issue we want to make sure we get right, including possibly factoring out our model provider class.
We'll get back to you soon!

**Comment by krrishdholakia** [comment]
bump on this? @joshreini1

**Comment by joshreini1** [comment]
> bump on this? @joshreini1

We're working on refactoring model providers this week. It'll make more sense to put this in after the refactor is done.

**Comment by ishaan-jaff** [comment]
@joshreini1 any update on this ?

**Comment by joshreini1** [comment]
> @joshreini1 any update on this ?

Yep - here's the WIP [PR](https://github.com/truera/trulens/pull/411) in question. This is slotted for the release this week. Depending on when it's done, we may be able to get the litellm in the same release.

**Comment by joshreini1** [comment]
@ishaan-jaff I started a new PR for this to add LiteLLM as a model provider. Can you take a look?

https://github.com/truera/trulens/pull/455

**Pull request closed without merging**
