### PR TITLE
Formatter pre-commit hook

### PR DESCRIPTION
**Pull request by sfc-gh-jreini**
# Description

Adding a precommit hook for formatting.

## Other details good to know for developers

To add the change to your local development environment, run from root:
```bash
sh setup-hooks.sh
```

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

### CODE REVIEW

**Review by sfc-gh-dkurokawa — COMMENTED** [review]
I only just read about the pre-commit stuff, but is there a reason you don't just change the `.git/hooks/pre-commit` file directly?

**Comment by sfc-gh-jreini** [comment]
> I only just read about the pre-commit stuff, but is there a reason you don't just change the `.git/hooks/pre-commit` file directly?

My understanding is that the `.git` folder isn't versioned

**Comment by sfc-gh-chu** [comment]
> > I only just read about the pre-commit stuff, but is there a reason you don't just change the `.git/hooks/pre-commit` file directly?
> 
> My understanding is that the `.git` folder isn't versioned. Also this way devs can choose to use or not this hook

Have we taken a look at [precommit](https://pre-commit.com/)? yapf and isort are both supported as a config there

**Comment by sfc-gh-jreini** [comment]
> > > I only just read about the pre-commit stuff, but is there a reason you don't just change the `.git/hooks/pre-commit` file directly?
> > 
> > 
> > My understanding is that the `.git` folder isn't versioned. Also this way devs can choose to use or not this hook
> 
> Have we taken a look at [precommit](https://pre-commit.com/)? yapf and isort are both supported as a config there



> > > I only just read about the pre-commit stuff, but is there a reason you don't just change the `.git/hooks/pre-commit` file directly?
> > 
> > 
> > My understanding is that the `.git` folder isn't versioned. Also this way devs can choose to use or not this hook
> 
> Have we taken a look at [precommit](https://pre-commit.com/)? yapf and isort are both supported as a config there

Would that be easier? Since our format.sh is nonstandard, wouldn't we have to configure that anyway with precommit?

**Comment by sfc-gh-jreini** [comment]
Closing, will by done by #1303

**Pull request closed without merging**
