### PR TITLE
[MLNN-1072] Add feedback direction `higher_is_better` by default

### PR DESCRIPTION
**Pull request by ejisoo**
## Changes

* Add class attribute `higher_is_better` for `Feedback`. By default, higher scores are better. (**TODO**: add direction to v2? Is this needed?)
* Change `CATEGORY` to support styling for both directions. Keep `(0, 0.6, 0.8)` (worst, medium/bad, high/good) thresholds for the positive direction and add `(0.2, 0.4, 1)` (low/good, medium/bad, worst). (**TODO**: make thresholds configurable for each feedback function and/or each app?)
* Update `Leaderboard` and `Evaluations` to accommodate new styling
* Code formatting (isort & yapf) - created a bit of diff for existing code
* ~~Add/update a notebook to show feedback functions with negative direction (e.g., harmfulness or toxicity)~~ Use the new demo notebook and add a screenshot
* Change OpenAI moderation category scores to normal direction (lower is better)
* Update moderation API test cases accordingly

### Caveat

* `CATEGORY` returning a list of dictionaries isn't ideal, but this was one of the easier ways to keep `styles` from importing additional non-UI modules
* Direction is implemented in `Feedback` not `FeedbackDefinition` since it doesn't need de/serialization logic (@piotrm0 could comment on this maybe)
* Feedback's `.on*` methods need any additional feedback function-level arguments to be provided for each variant such methods update

### CODE REVIEW

**Comment by joshreini1** [comment]
Can you modify an existing notebook to show how this is used?

**Comment by ejisoo** [comment]
@joshreini1 I used your new demo notebook and defined
```
f_controversiality = Feedback(
    openai.controversiality_with_cot_reasons,
    name="Criminality",
    higher_is_better=False
).on_output()
f_criminality = Feedback(
    openai.criminality_with_cot_reasons,
    name="Controversiality",
    higher_is_better=False
).on_output()
f_harmfulness = Feedback(
    openai.harmfulness_with_cot_reasons,
    name="Harmfulness",
    higher_is_better=False
).on_output()
```
and so on for the first RAG.

Feedbacks are computing now:

image

**Review by joshreini1 — APPROVED** [review]
This will make a huge difference in usability and help increase adoption of these feedback functions. Changes look good to me!

**Comment by ejisoo** [comment]
The moderation category scores are used as returned by the API now. Confirming low scores are good scores for them.

image

**Review by joshreini1 — APPROVED** [review]
Lgtm!

**Pull request merged**
